-- AlterTable
ALTER TABLE "dashboard_kpi_snapshots" ADD COLUMN     "avgPerformanceScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "conversionRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "convertedLeads" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "newLeads" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "onLeaveToday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rebuiltAt" TIMESTAMP(3),
ADD COLUMN     "topPerformers" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "totalBookings" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalEmployees" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalLeads" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalProperties" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSiteVisits" INTEGER NOT NULL DEFAULT 0;
