import { Injectable, Logger } from '@nestjs/common';
import { PDFDocument, rgb, degrees } from 'pdf-lib';
import { Quotation } from '@prisma/client';

@Injectable()
export class QuotationPdfService {
  private readonly logger = new Logger(QuotationPdfService.name);

  async generateWatermarkedPdf(
    quotation: Quotation & { companies: any; createdBy: any },
    downloadedByEmail: string,
  ): Promise<Buffer> {
    // In a real implementation, you would load a template PDF or generate it fully.
    // For this ERP implementation phase, we generate a basic PDF and watermark it as required.
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 800]);
    const { width, height } = page.getSize();

    // Draw basic quotation details
    page.drawText(`Quotation: ${quotation.referenceNumber}`, {
      x: 50,
      y: height - 50,
      size: 20,
    });
    page.drawText(`Company: ${quotation.companies.name}`, {
      x: 50,
      y: height - 80,
      size: 12,
    });
    page.drawText(`Total Amount: ${quotation.totalAmount.toString()}`, {
      x: 50,
      y: height - 110,
      size: 12,
    });
    page.drawText(`Status: ${quotation.status}`, {
      x: 50,
      y: height - 140,
      size: 12,
    });
    page.drawText(`Generated By: ${quotation.createdBy?.userId || 'System'}`, {
      x: 50,
      y: height - 170,
      size: 12,
    });

    // Draw breakdown
    const breakdown =
      typeof quotation.breakdown === 'object'
        ? JSON.stringify(quotation.breakdown)
        : '{}';
    page.drawText(`Breakdown: ${breakdown}`, {
      x: 50,
      y: height - 200,
      size: 10,
    });

    // Apply security watermark required by SRS Section 10
    const watermarkText = `CONFIDENTIAL - Downloaded by: ${downloadedByEmail} at ${new Date().toISOString()}`;
    page.drawText(watermarkText, {
      x: 50,
      y: height / 2 - 100,
      size: 24,
      color: rgb(0.75, 0.75, 0.75),
      rotate: degrees(45),
      opacity: 0.3,
    });

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }
}
