export enum DomainEventTypes {
  // Task Events
  TASK_CREATED = 'TASK_CREATED',
  TASK_ACKNOWLEDGED = 'TASK_ACKNOWLEDGED',
  TASK_OVERDUE = 'TASK_OVERDUE',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_COMPLETION_ACKNOWLEDGED = 'TASK_COMPLETION_ACKNOWLEDGED',
  TASK_COMPLETION_APPROVED = 'TASK_COMPLETION_APPROVED',
  TASK_REASSIGNED = 'TASK_REASSIGNED',
  TASK_ESCALATED_MANAGER = 'TASK_ESCALATED_MANAGER',
  TASK_ESCALATED_HR = 'TASK_ESCALATED_HR',
  TASK_PROOF_REJECTED = 'TASK_PROOF_REJECTED',
  TASK_PROOF_ESCALATED_HR = 'TASK_PROOF_ESCALATED_HR',
  TASK_EXTENSION_REQUESTED = 'TASK_EXTENSION_REQUESTED',
  TASK_EXTENSION_APPROVED = 'TASK_EXTENSION_APPROVED',
  TASK_EXTENSION_REJECTED = 'TASK_EXTENSION_REJECTED',
  TASK_SLA_REMINDER = 'task.sla.reminder',
  TASK_SLA_BREACHED = 'task.sla.breached',

  // Warning Events
  WARNING_CREATED = 'WARNING_CREATED',
  WARNING_APPROVED = 'WARNING_APPROVED',
  WARNING_REJECTED = 'WARNING_REJECTED',
  WARNING_ACKNOWLEDGED = 'WARNING_ACKNOWLEDGED',
  DISCIPLINARY_REVIEW_TRIGGERED = 'DISCIPLINARY_REVIEW_TRIGGERED',
  WARNING_THRESHOLD_BREACHED = 'WARNING_THRESHOLD_BREACHED',
  WARNING_EXPIRED = 'WARNING_EXPIRED',

  // Approval Events
  APPROVAL_CREATED = 'APPROVAL_CREATED',
  APPROVAL_APPROVED = 'APPROVAL_APPROVED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  APPROVAL_ESCALATED = 'APPROVAL_ESCALATED',
  APPROVAL_OVERRIDDEN = 'APPROVAL_OVERRIDDEN',

  // Payroll Hold Events
  PAYROLL_HOLD_RECOMMENDED = 'PAYROLL_HOLD_RECOMMENDED',
  PAYROLL_HOLD_ACTIVATED = 'PAYROLL_HOLD_ACTIVATED',
  PAYROLL_HOLD_REJECTED = 'PAYROLL_HOLD_REJECTED',
  PAYROLL_HOLD_RELEASE_REQUESTED = 'PAYROLL_HOLD_RELEASE_REQUESTED',
  PAYROLL_HOLD_RELEASED = 'PAYROLL_HOLD_RELEASED',
  PAYROLL_HOLD_ESCALATED = 'PAYROLL_HOLD_ESCALATED',
  OWNER_EMERGENCY_HOLD = 'OWNER_EMERGENCY_HOLD',

  // Attendance & Leave Events
  ATTENDANCE_PUNCH_RECORDED = 'ATTENDANCE_PUNCH_RECORDED',
  ATTENDANCE_EVIDENCE_PENDING = 'ATTENDANCE_EVIDENCE_PENDING',
  ATTENDANCE_SESSION_CLOSED = 'ATTENDANCE_SESSION_CLOSED',
  ATTENDANCE_FINALIZATION_BATCH_STARTED = 'ATTENDANCE_FINALIZATION_BATCH_STARTED',
  ATTENDANCE_FINALIZED = 'ATTENDANCE_FINALIZED',
  ATTENDANCE_FINALIZATION_BATCH_COMPLETED = 'ATTENDANCE_FINALIZATION_BATCH_COMPLETED',
  ATTENDANCE_PERIOD_LOCKED = 'ATTENDANCE_PERIOD_LOCKED',
  ATTENDANCE_CORRECTION_REQUESTED = 'ATTENDANCE_CORRECTION_REQUESTED',
  ATTENDANCE_CORRECTION_APPROVED = 'ATTENDANCE_CORRECTION_APPROVED',
  ATTENDANCE_CORRECTION_REJECTED = 'ATTENDANCE_CORRECTION_REJECTED',
  ATTENDANCE_EVIDENCE_REVIEWED = 'ATTENDANCE_EVIDENCE_REVIEWED',
  LEAVE_REQUESTED = 'LEAVE_REQUESTED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',

  // Payroll Events
  PAYROLL_PROCESSED = 'PAYROLL_PROCESSED',

  // Performance Events
  PERFORMANCE_SCORE_CALCULATED = 'PERFORMANCE_SCORE_CALCULATED',
  MANAGER_RATING_RECORDED = 'MANAGER_RATING_RECORDED',

  // Communication Events
  ANNOUNCEMENT_CREATED = 'ANNOUNCEMENT_CREATED',
  ANNOUNCEMENT_PUBLISHED = 'ANNOUNCEMENT_PUBLISHED',
  ANNOUNCEMENT_ARCHIVED = 'ANNOUNCEMENT_ARCHIVED',
  ANNOUNCEMENT_READ = 'ANNOUNCEMENT_READ',
  ANNOUNCEMENT_ACKNOWLEDGED = 'ANNOUNCEMENT_ACKNOWLEDGED',

  // Document Events
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_ACCESSED = 'DOCUMENT_ACCESSED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',

  // CRM Events
  LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',
  SITE_VISIT_SCHEDULED = 'SITE_VISIT_SCHEDULED',
  SITE_VISIT_COMPLETED = 'SITE_VISIT_COMPLETED',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  PROPERTY_CREATED = 'PROPERTY_CREATED',
  PROPERTY_STATUS_CHANGED = 'PROPERTY_STATUS_CHANGED',
}

export interface BaseDomainEventPayload {
  companyId: string;
  [key: string]: any;
}
