-- Add missing UserRole enum values that were in schema but not in migrations
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ACCOUNTS' AFTER 'HR_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGER' AFTER 'ACCOUNTS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TEAM_LEAD' AFTER 'MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FIELD_EMPLOYEE' AFTER 'EMPLOYEE';
