export const Permissions = {
  USER_READ: 'user:read',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',

  EMPLOYEE_READ: 'employee:read',
  EMPLOYEE_CREATE: 'employee:create',
  EMPLOYEE_UPDATE: 'employee:update',
  EMPLOYEE_DELETE: 'employee:delete',
  EMPLOYEE_VIEW_SALARY: 'employee:view-salary',

  DEPARTMENT_READ: 'department:read',
  DEPARTMENT_CREATE: 'department:create',
  DEPARTMENT_UPDATE: 'department:update',
  DEPARTMENT_DELETE: 'department:delete',

  DESIGNATION_READ: 'designation:read',
  DESIGNATION_CREATE: 'designation:create',
  DESIGNATION_UPDATE: 'designation:update',
  DESIGNATION_DELETE: 'designation:delete',

  PROPERTY_READ: 'property:read',
  PROPERTY_CREATE: 'property:create',
  PROPERTY_UPDATE: 'property:update',
  PROPERTY_DELETE: 'property:delete',

  LEAD_READ: 'lead:read',
  LEAD_CREATE: 'lead:create',
  LEAD_UPDATE: 'lead:update',
  LEAD_DELETE: 'lead:delete',
  LEAD_CONVERT: 'lead:convert',
  LEAD_FOLLOWUP_READ: 'lead:followup:read',
  LEAD_FOLLOWUP_CREATE: 'lead:followup:create',

  QUOTATION_READ: 'quotation:read',
  QUOTATION_CREATE: 'quotation:create',
  QUOTATION_UPDATE: 'quotation:update',
  QUOTATION_DOWNLOAD: 'quotation:download',

  CUSTOMER_READ: 'customer:read',
  CUSTOMER_CREATE: 'customer:create',
  CUSTOMER_UPDATE: 'customer:update',
  CUSTOMER_DELETE: 'customer:delete',

  SITE_VISIT_READ: 'site-visit:read',
  SITE_VISIT_CREATE: 'site-visit:create',
  SITE_VISIT_UPDATE: 'site-visit:update',
  SITE_VISIT_DELETE: 'site-visit:delete',

  BOOKING_READ: 'booking:read',
  BOOKING_CREATE: 'booking:create',
  BOOKING_UPDATE: 'booking:update',
  BOOKING_DELETE: 'booking:delete',

  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_CREATE: 'attendance:create',
  ATTENDANCE_VERIFY: 'attendance:verify',

  LEAVE_READ: 'leave:read',
  LEAVE_CREATE: 'leave:create',
  LEAVE_APPROVE: 'leave:approve',

  NOTIFICATION_READ: 'notification:read',
  NOTIFICATION_SEND: 'notification:send',

  AUDIT_LOG_READ: 'audit-log:read',

  PERFORMANCE_READ: 'performance:read',
  PERFORMANCE_CALCULATE: 'performance:calculate',
  PERFORMANCE_RATE: 'performance:rate',
  PERFORMANCE_TREND: 'performance:trend',
  PERFORMANCE_LEADERBOARD: 'performance:leaderboard',

  ANNOUNCEMENT_READ: 'announcement:read',
  ANNOUNCEMENT_CREATE: 'announcement:create',
  ANNOUNCEMENT_PUBLISH: 'announcement:publish',
  ANNOUNCEMENT_ARCHIVE: 'announcement:archive',

  DOCUMENT_READ: 'document:read',
  DOCUMENT_CREATE: 'document:create',
  DOCUMENT_DELETE: 'document:delete',

  DASHBOARD_VIEW: 'dashboard:view',
  REPORT_VIEW: 'report:view',
  REPORT_EXPORT: 'report:export',
  EXPORT_CONFIG_READ: 'export-config:read',
  EXPORT_CONFIG_MANAGE: 'export-config:manage',
  EXPORT_SHEET_SYNC: 'export-sheet:sync',
  EXPORT_DOWNLOAD: 'export:download',
  EXPORT_HISTORY: 'export:history',
  ANALYTICS_VIEW: 'analytics:view',

  TASK_ASSIGN: 'task:assign',
  TASK_ESCALATE: 'task:escalate',
  TASK_COMPLETION_ACKNOWLEDGE: 'task:completion:acknowledge',
  TASK_COMPLETION_APPROVE: 'task:completion:approve',
  APPROVAL_READ: 'approval:read',
  APPROVAL_MANAGE: 'approval:manage',
  PAYROLL_PROCESS: 'payroll:process',
  PAYROLL_HOLD_CREATE: 'payroll:hold:create',
  PAYROLL_HOLD_RELEASE: 'payroll:hold:release',
  WARNING_READ: 'warning:read',
  WARNING_CREATE: 'warning:create',
  WARNING_ISSUE: 'warning:issue',
  WARNING_ACKNOWLEDGE: 'warning:acknowledge',
  EXPORT_SENSITIVE: 'export:sensitive',
  ATTENDANCE_APPROVE: 'attendance:approve',
  DELETION_AUTHORIZE: 'deletion:authorize',

  // Phase 5 Permissions
  AGREEMENT_READ: 'agreement:read',
  AGREEMENT_CREATE: 'agreement:create',
  AGREEMENT_APPROVE: 'agreement:approve',
  PROFITABILITY_VIEW: 'profitability:view',
  RECRUITMENT_READ: 'recruitment:read',
  RECRUITMENT_CREATE: 'recruitment:create',
  RECRUITMENT_UPDATE: 'recruitment:update',
  TRAINING_READ: 'training:read',
  TRAINING_CREATE: 'training:create',
  TRAINING_ACKNOWLEDGE: 'training:acknowledge',
  ASSET_READ: 'asset:read',
  ASSET_CREATE: 'asset:create',
  ASSET_UPDATE: 'asset:update',
  ASSET_DELETE: 'asset:delete',
  ASSET_ASSIGN: 'asset:assign',
  ASSET_REPAIR: 'asset:repair',
  MEETING_READ: 'meeting:read',
  MEETING_CREATE: 'meeting:create',
  MEETING_RECORD_MOM: 'meeting:record-mom',

  // Payment & Expense Permissions
  PAYMENT_READ: 'payment:read',
  PAYMENT_CREATE: 'payment:create',
  PAYMENT_UPDATE: 'payment:update',
  PAYMENT_DELETE: 'payment:delete',
  EXPENSE_READ: 'expense:read',
  EXPENSE_CREATE: 'expense:create',
  EXPENSE_APPROVE: 'expense:approve',

  // Chart of Account Permissions
  ACCOUNT_READ: 'account:read',
  ACCOUNT_CREATE: 'account:create',
  ACCOUNT_UPDATE: 'account:update',
  ACCOUNT_DELETE: 'account:delete',

  // Commission & Incentive Permissions
  COMMISSION_READ: 'commission:read',
  COMMISSION_UPDATE: 'commission:update',
  INCENTIVE_READ: 'incentive:read',
  INCENTIVE_CREATE: 'incentive:create',

  // Payroll Permissions (extending existing)
  PAYROLL_READ: 'payroll:read',

  // Construction Permissions
  CONSTRUCTION_READ: 'construction:read',
  CONSTRUCTION_CREATE: 'construction:create',
  CONSTRUCTION_UPDATE: 'construction:update',
  CONSTRUCTION_DELETE: 'construction:delete',
  CONSUMPTION_CREATE: 'consumption:create',
  CONSUMPTION_READ: 'consumption:read',
  CONSUMPTION_DELETE: 'consumption:delete',

  // Complaint Permissions
  COMPLAINT_READ: 'complaint:read',
  COMPLAINT_CREATE: 'complaint:create',
  COMPLAINT_UPDATE: 'complaint:update',

  // Escalation Permissions
  ESCALATION_READ: 'escalation:read',
  ESCALATION_CREATE: 'escalation:create',
  ESCALATION_DELETE: 'escalation:delete',

  // Assignment Permissions
  ASSIGNMENT_READ: 'assignment:read',
  ASSIGNMENT_CREATE: 'assignment:create',

  // EMS Permissions
  EMS_READ: 'ems:read',
  EMS_CREATE: 'ems:create',

  // Company Permissions
  COMPANY_READ: 'company:read',
  COMPANY_UPDATE: 'company:update',

  // EOD Permissions
  EOD_READ: 'eod:read',
  EOD_CREATE: 'eod:create',
  EOD_REVIEW: 'eod:review',

  // Security & Device Permissions
  SECURITY_READ: 'security:read',
  SECURITY_UPDATE: 'security:update',
  DEVICE_READ: 'device:read',
  DEVICE_CREATE: 'device:create',
  DEVICE_UPDATE: 'device:update',
  DEVICE_DELETE: 'device:delete',

  // Broker Permissions
  BROKER_READ: 'broker:read',
  BROKER_CREATE: 'broker:create',
  BROKER_UPDATE: 'broker:update',
  BROKER_DELETE: 'broker:delete',

  // Inventory Permissions
  INVENTORY_READ: 'inventory:read',
  INVENTORY_CREATE: 'inventory:create',
  INVENTORY_UPDATE: 'inventory:update',
  INVENTORY_DELETE: 'inventory:delete',
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];

import { UserRole } from '@prisma/client';

const rolePermissions: Record<UserRole, Permission[]> = {
  OWNER: Object.values(Permissions),
  ADMIN: Object.values(Permissions),
  HR_MANAGER: [
    Permissions.DASHBOARD_VIEW,
    Permissions.REPORT_VIEW,
    Permissions.REPORT_EXPORT,
    Permissions.ANALYTICS_VIEW,
    Permissions.EMPLOYEE_READ,
    Permissions.EMPLOYEE_CREATE,
    Permissions.EMPLOYEE_UPDATE,
    Permissions.EMPLOYEE_VIEW_SALARY,
    Permissions.DEPARTMENT_READ,
    Permissions.DEPARTMENT_CREATE,
    Permissions.DEPARTMENT_UPDATE,
    Permissions.DESIGNATION_READ,
    Permissions.DESIGNATION_CREATE,
    Permissions.DESIGNATION_UPDATE,
    Permissions.LEAVE_READ,
    Permissions.LEAVE_CREATE,
    Permissions.LEAVE_APPROVE,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_CREATE,
    Permissions.ATTENDANCE_VERIFY,
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_SEND,
    Permissions.USER_READ,
    Permissions.AUDIT_LOG_READ,
    Permissions.PERFORMANCE_READ,
    Permissions.PERFORMANCE_CALCULATE,
    Permissions.PERFORMANCE_RATE,
    Permissions.PERFORMANCE_TREND,
    Permissions.PERFORMANCE_LEADERBOARD,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.ANNOUNCEMENT_CREATE,
    Permissions.ANNOUNCEMENT_PUBLISH,
    Permissions.ANNOUNCEMENT_ARCHIVE,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_CREATE,
    Permissions.DOCUMENT_DELETE,
    Permissions.EXPORT_CONFIG_READ,
    Permissions.EXPORT_CONFIG_MANAGE,
    Permissions.PAYROLL_READ,
    Permissions.PAYROLL_PROCESS,
    Permissions.PAYROLL_HOLD_CREATE,
    Permissions.PAYROLL_HOLD_RELEASE,
    Permissions.WARNING_ISSUE,
    Permissions.WARNING_ACKNOWLEDGE,
    Permissions.WARNING_READ,
    Permissions.WARNING_CREATE,
    Permissions.EXPENSE_READ,
    Permissions.EXPENSE_APPROVE,
    Permissions.COMMISSION_READ,
    Permissions.COMMISSION_UPDATE,
    Permissions.INCENTIVE_READ,
    Permissions.INCENTIVE_CREATE,
    Permissions.CONSTRUCTION_READ,
    Permissions.CONSTRUCTION_CREATE,
    Permissions.EOD_READ,
    Permissions.EOD_CREATE,
    Permissions.EOD_REVIEW,
    Permissions.COMPLAINT_READ,
    Permissions.COMPLAINT_CREATE,
    Permissions.COMPLAINT_UPDATE,
    Permissions.DEVICE_READ,
    Permissions.DEVICE_CREATE,
    Permissions.DEVICE_UPDATE,
    Permissions.EMS_READ,
    Permissions.EMS_CREATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_CREATE,
    Permissions.INVENTORY_UPDATE,
    Permissions.PROPERTY_READ,
    Permissions.LEAD_READ,
    Permissions.LEAD_FOLLOWUP_READ,
    Permissions.CUSTOMER_READ,
    Permissions.BROKER_READ,
    Permissions.SITE_VISIT_READ,
    Permissions.BOOKING_READ,
    Permissions.TRAINING_READ,
    Permissions.TRAINING_CREATE,
    Permissions.TRAINING_ACKNOWLEDGE,
    Permissions.ASSET_READ,
    Permissions.ASSET_CREATE,
    Permissions.ASSET_UPDATE,
    Permissions.ASSET_DELETE,
    Permissions.ASSET_ASSIGN,
    Permissions.ASSET_REPAIR,
    Permissions.MEETING_READ,
    Permissions.MEETING_CREATE,
    Permissions.MEETING_RECORD_MOM,
    Permissions.AGREEMENT_READ,
    Permissions.AGREEMENT_CREATE,
    Permissions.AGREEMENT_APPROVE,
    Permissions.RECRUITMENT_READ,
    Permissions.RECRUITMENT_CREATE,
    Permissions.RECRUITMENT_UPDATE,
    Permissions.COMPANY_READ,
    Permissions.TASK_COMPLETION_ACKNOWLEDGE,
    Permissions.TASK_COMPLETION_APPROVE,
  ],
  ACCOUNTS: [
    Permissions.DASHBOARD_VIEW,
    Permissions.REPORT_VIEW,
    Permissions.REPORT_EXPORT,
    Permissions.ANALYTICS_VIEW,
    Permissions.EMPLOYEE_READ,
    Permissions.EMPLOYEE_VIEW_SALARY,
    Permissions.LEAVE_READ,
    Permissions.ATTENDANCE_READ,
    Permissions.PERFORMANCE_READ,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.DOCUMENT_READ,
    Permissions.EXPORT_CONFIG_READ,
    Permissions.EXPORT_DOWNLOAD,
    Permissions.EXPORT_HISTORY,
    Permissions.PAYMENT_READ,
    Permissions.PAYMENT_CREATE,
    Permissions.PAYMENT_UPDATE,
    Permissions.ACCOUNT_READ,
    Permissions.ACCOUNT_CREATE,
    Permissions.ACCOUNT_UPDATE,
    Permissions.EXPENSE_READ,
    Permissions.EXPENSE_CREATE,
    Permissions.EXPENSE_APPROVE,
    Permissions.COMMISSION_READ,
    Permissions.BROKER_READ,
    Permissions.PAYROLL_READ,
    Permissions.CONSTRUCTION_READ,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_CREATE,
    Permissions.ASSET_READ,
    Permissions.PAYROLL_PROCESS,
    Permissions.PROFITABILITY_VIEW,
  ],
  MANAGER: [
    Permissions.DASHBOARD_VIEW,
    Permissions.ANALYTICS_VIEW,
    Permissions.EMPLOYEE_READ,
    Permissions.LEAVE_READ,
    Permissions.LEAVE_CREATE,
    Permissions.LEAVE_APPROVE,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_VERIFY,
    Permissions.PERFORMANCE_READ,
    Permissions.PERFORMANCE_RATE,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.DOCUMENT_READ,
    Permissions.CONSTRUCTION_READ,
    Permissions.EOD_READ,
    Permissions.EOD_CREATE,
    Permissions.EOD_REVIEW,
    Permissions.COMPLAINT_READ,
    Permissions.COMPLAINT_CREATE,
    Permissions.COMPLAINT_UPDATE,
    Permissions.DEVICE_READ,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_CREATE,
    Permissions.PROPERTY_READ,
    Permissions.DESIGNATION_READ,
    Permissions.DESIGNATION_CREATE,
    Permissions.DESIGNATION_UPDATE,
    Permissions.DEPARTMENT_READ,
    Permissions.DEPARTMENT_CREATE,
    Permissions.DEPARTMENT_UPDATE,
    Permissions.TRAINING_READ,
    Permissions.TRAINING_CREATE,
    Permissions.TRAINING_ACKNOWLEDGE,
    Permissions.ASSET_READ,
    Permissions.MEETING_READ,
    Permissions.MEETING_CREATE,
    Permissions.AGREEMENT_READ,
    Permissions.AGREEMENT_APPROVE,
    Permissions.LEAD_READ,
    Permissions.NOTIFICATION_READ,
    Permissions.CUSTOMER_READ,
    Permissions.BROKER_READ,
    Permissions.BROKER_CREATE,
    Permissions.SITE_VISIT_READ,
    Permissions.BOOKING_READ,
    Permissions.TASK_ASSIGN,
    Permissions.TASK_ESCALATE,
    Permissions.TASK_COMPLETION_ACKNOWLEDGE,
    Permissions.WARNING_READ,
    Permissions.WARNING_CREATE,
    Permissions.WARNING_ISSUE,
    Permissions.APPROVAL_READ,
  ],
  TEAM_LEAD: [
    Permissions.DASHBOARD_VIEW,
    Permissions.EMPLOYEE_READ,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_VERIFY,
    Permissions.PERFORMANCE_READ,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.DOCUMENT_READ,
    Permissions.PROPERTY_READ,
    Permissions.LEAD_READ,
    Permissions.LEAVE_CREATE,
    Permissions.TRAINING_READ,
    Permissions.TRAINING_ACKNOWLEDGE,
    Permissions.MEETING_READ,
    Permissions.NOTIFICATION_READ,
    Permissions.EOD_READ,
    Permissions.DEVICE_READ,
    Permissions.TASK_ASSIGN,
    Permissions.TASK_COMPLETION_ACKNOWLEDGE,
    Permissions.WARNING_READ,
    Permissions.APPROVAL_READ,
    Permissions.INVENTORY_READ,
  ],
  EMPLOYEE: [
    Permissions.DASHBOARD_VIEW,
    Permissions.ANALYTICS_VIEW,
    Permissions.EMPLOYEE_READ,
    Permissions.PROPERTY_READ,
    Permissions.LEAD_READ,
    Permissions.LEAD_CREATE,
    Permissions.LEAD_UPDATE,
    Permissions.LEAD_CONVERT,
    Permissions.LEAD_FOLLOWUP_READ,
    Permissions.LEAD_FOLLOWUP_CREATE,
    Permissions.QUOTATION_READ,
    Permissions.QUOTATION_CREATE,
    Permissions.CUSTOMER_READ,
    Permissions.CUSTOMER_CREATE,
    Permissions.CUSTOMER_UPDATE,
    Permissions.BROKER_READ,
    Permissions.BROKER_CREATE,
    Permissions.BROKER_UPDATE,
    Permissions.SITE_VISIT_READ,
    Permissions.SITE_VISIT_CREATE,
    Permissions.SITE_VISIT_UPDATE,
    Permissions.BOOKING_READ,
    Permissions.BOOKING_CREATE,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_CREATE,
    Permissions.LEAVE_READ,
    Permissions.LEAVE_CREATE,
    Permissions.NOTIFICATION_READ,
    Permissions.PERFORMANCE_READ,
    Permissions.PERFORMANCE_TREND,
    Permissions.PERFORMANCE_LEADERBOARD,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_CREATE,
    Permissions.EOD_READ,
    Permissions.EOD_CREATE,
    Permissions.DEVICE_READ,
    Permissions.DEVICE_CREATE,
    Permissions.EMS_READ,
    Permissions.EMS_CREATE,
    Permissions.INVENTORY_READ,
    Permissions.INCENTIVE_READ,
    Permissions.TRAINING_READ,
    Permissions.TRAINING_ACKNOWLEDGE,
    Permissions.MEETING_READ,
    Permissions.WARNING_READ,
    Permissions.WARNING_ACKNOWLEDGE,
    Permissions.TASK_ASSIGN,
  ],
  FIELD_EMPLOYEE: [
    Permissions.DASHBOARD_VIEW,
    Permissions.EMPLOYEE_READ,
    Permissions.PROPERTY_READ,
    Permissions.LEAD_READ,
    Permissions.LEAD_CREATE,
    Permissions.LEAD_UPDATE,
    Permissions.LEAD_FOLLOWUP_READ,
    Permissions.LEAD_FOLLOWUP_CREATE,
    Permissions.SITE_VISIT_READ,
    Permissions.SITE_VISIT_CREATE,
    Permissions.SITE_VISIT_UPDATE,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_CREATE,
    Permissions.LEAVE_READ,
    Permissions.LEAVE_CREATE,
    Permissions.NOTIFICATION_READ,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_CREATE,
    Permissions.EOD_READ,
    Permissions.EOD_CREATE,
    Permissions.DEVICE_READ,
    Permissions.DEVICE_CREATE,
    Permissions.CONSTRUCTION_READ,
    Permissions.INVENTORY_READ,
    Permissions.TRAINING_READ,
    Permissions.TRAINING_ACKNOWLEDGE,
    Permissions.TASK_ASSIGN,
  ],
};

export function getPermissionsForRole(role: UserRole): Permission[] {
  return rolePermissions[role] ?? [];
}

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return getPermissionsForRole(role).includes(permission);
}

export function mergePermissionsWithGrants(
  rolePermissions: Permission[],
  grants: { permission: string; granted: boolean }[],
): Permission[] {
  const grantMap = new Map(grants.map((g) => [g.permission, g.granted]));
  const effective = new Set(rolePermissions);

  for (const [perm, granted] of grantMap) {
    if (granted) {
      effective.add(perm as Permission);
    } else {
      effective.delete(perm as Permission);
    }
  }

  return Array.from(effective);
}
